# Atividade sobre validação cruzada

Para esta atividade, você deve implementar o conceito básico por trás da validação cruzada.

Para isso, você deve criar uma função que, dada uma lista com os índices das linhas de um dataframe e o número de folds (pastas), retorne os subconjuntos para aplicar a validação cruzada.

In [169]:
def get_folds(indices, n_folds):
    size = len(indices)
    subset_size = round(size / n_folds)
    subsets = [indices[x:x+subset_size] for x in range(0, len(indices), subset_size)]
    conjunto = []
    for i in range(n_folds):
        test = subsets[i]
        train = []
        for subset in subsets:
            if subset != test:
                train = train + subset
        conjunto.append([train, test])
    return conjunto

get_folds(indices, 2)

[[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],
 [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]]

Após criar sua função, utilize o código abaixo para verificar se sua função está executando corretamente. 

Note que o código abaixo foi constrído pensando que o retorno da função get_folds é uma lista de tuplas, onde o primeiro elemento da tupla é o conjunto com os índices de treino e o segundo o conjunto com os ínidces de teste.

In [170]:
import pandas as pd

df = pd.DataFrame({"col1": range(20), "col2": map(lambda n: chr(n), range(97, 117))})

df

    col1 col2
0      0    a
1      1    b
2      2    c
3      3    d
4      4    e
5      5    f
6      6    g
7      7    h
8      8    i
9      9    j
10    10    k
11    11    l
12    12    m
13    13    n
14    14    o
15    15    p
16    16    q
17    17    r
18    18    s
19    19    t

In [0]:
def verifica_conjuntos_cv(df, conjuntos):
    for i in range(len(conjuntos)):
        ind_treino = conjuntos[i][0]
        ind_teste = conjuntos[i][1]
        
        print("Conjunto {}:".format(i + 1))
        
        print("Treino:")
        print(df.iloc[ind_treino])
        
        print("Teste:")
        print(df.iloc[ind_teste])

In [172]:
indices = list(df.index)

# 2 folds
verifica_conjuntos_cv(df, get_folds(indices, 2))

Conjunto 1:
Treino:
    col1 col2
10    10    k
11    11    l
12    12    m
13    13    n
14    14    o
15    15    p
16    16    q
17    17    r
18    18    s
19    19    t
Teste:
   col1 col2
0     0    a
1     1    b
2     2    c
3     3    d
4     4    e
5     5    f
6     6    g
7     7    h
8     8    i
9     9    j
Conjunto 2:
Treino:
   col1 col2
0     0    a
1     1    b
2     2    c
3     3    d
4     4    e
5     5    f
6     6    g
7     7    h
8     8    i
9     9    j
Teste:
    col1 col2
10    10    k
11    11    l
12    12    m
13    13    n
14    14    o
15    15    p
16    16    q
17    17    r
18    18    s
19    19    t

In [173]:
# 5 folds
verifica_conjuntos_cv(df, get_folds(indices, 5))

Conjunto 1:
Treino:
    col1 col2
4      4    e
5      5    f
6      6    g
7      7    h
8      8    i
9      9    j
10    10    k
11    11    l
12    12    m
13    13    n
14    14    o
15    15    p
16    16    q
17    17    r
18    18    s
19    19    t
Teste:
   col1 col2
0     0    a
1     1    b
2     2    c
3     3    d
Conjunto 2:
Treino:
    col1 col2
0      0    a
1      1    b
2      2    c
3      3    d
8      8    i
9      9    j
10    10    k
11    11    l
12    12    m
13    13    n
14    14    o
15    15    p
16    16    q
17    17    r
18    18    s
19    19    t
Teste:
   col1 col2
4     4    e
5     5    f
6     6    g
7     7    h
Conjunto 3:
Treino:
    col1 col2
0      0    a
1      1    b
2      2    c
3      3    d
4      4    e
5      5    f
6      6    g
7      7    h
12    12    m
13    13    n
14    14    o
15    15    p
16    16    q
17    17    r
18    18    s
19    19    t
Teste:
    col1 col2
8      8    i
9      9    j
10    10    k
11    11    l
Conjunto 4:
Treino:
    col1 col2
0      0    a
1      1    b
2      2    c
3      3    d
4      4    e
5      5    f
6      6    g
7      7    h
8      8    i
9      9    j
10    10    k
11    11    l
16    16    q
17    17    r
18    18    s
19    19    t
Teste:
    col1 col2
12    12    m
13    13    n
14    14    o
15    15    p
Conjunto 5:
Treino:
    col1 col2
0      0    a
1      1    b
2      2    c
3      3    d
4      4    e
5      5    f
6      6    g
7      7    h
8      8    i
9      9    j
10    10    k
11    11    l
12    12    m
13    13    n
14    14    o
15    15    p
Teste:
    col1 col2
16    16    q
17    17    r
18    18    s
19    19    t